name: test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        containers:
          - 1.18.10-bullseye
          - 1.19.9-bullseye
          - 1.20.4-bullseye
    runs-on: ubuntu-20.04
    container: golang:${{matrix.containers}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            /go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - run: pushd witness; go test -race -timeout=60s -v ./...; popd
      - run: pushd witness/wazero; go test -race -timeout=60s -v ./...; popd
      - run: pushd witness/wasmer; go test -race -timeout=60s -v ./...; popd
      - run: pushd witness/test_wasm_impls; go test -race -timeout=60s -v ./...; popd
